# Generated by Django 5.2.14 on 2026-05-10 20:40
"""Initial migration for the projects app."""

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=90, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=90, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("language", "Language"),
                            ("framework", "Framework"),
                            ("tool", "Tool"),
                            ("service", "Service"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "tech stack item",
                "verbose_name_plural": "tech stack",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="Short copy used on cards and meta descriptions."
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Markdown writeup rendered server-side."
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, upload_to="projects/heroes/"),
                ),
                ("hero_alt", models.CharField(blank=True, max_length=200)),
                ("is_published", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("repo_url", models.URLField(blank=True)),
                ("demo_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="projects.tag"
                    ),
                ),
                (
                    "tech_stack",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="projects.techstack"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
