# Generated by Django 5.2.14 on 2026-05-10 20:40
"""Initial migration for the about app."""

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("category", models.CharField(max_length=80)),
                ("months_of_use", models.PositiveSmallIntegerField(default=0)),
                ("proficiency", models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                "ordering": ["category", "-proficiency", "name"],
            },
        ),
        migrations.CreateModel(
            name="TimelineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("learning", "Learning"),
                            ("work", "Work"),
                            ("project", "Project"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "timeline entries",
                "ordering": ["-date"],
            },
        ),
    ]
