-- Simple schema reference for PrincetonAfeez/Personal-Portfolio-Website
-- Based on the Django models in: projects, about, and contact.
-- Use Django migrations as the source of truth for actual database creation.

CREATE TABLE projects_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    slug VARCHAR(90) NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT ''
);

CREATE TABLE projects_techstack (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    slug VARCHAR(90) NOT NULL UNIQUE,
    category VARCHAR(20) NOT NULL CHECK (category IN ('language', 'framework', 'tool', 'service'))
);

CREATE TABLE projects_project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    slug VARCHAR(200) NOT NULL UNIQUE,
    summary TEXT NOT NULL,
    body TEXT NOT NULL,
    hero_image VARCHAR(100) NOT NULL DEFAULT '',
    hero_alt VARCHAR(200) NOT NULL DEFAULT '',
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    published_at TIMESTAMP WITH TIME ZONE NULL,
    repo_url VARCHAR(200) NOT NULL DEFAULT '',
    demo_url VARCHAR(200) NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE projects_project_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects_project(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES projects_tag(id) ON DELETE CASCADE,
    UNIQUE (project_id, tag_id)
);

CREATE TABLE projects_project_tech_stack (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects_project(id) ON DELETE CASCADE,
    techstack_id BIGINT NOT NULL REFERENCES projects_techstack(id) ON DELETE CASCADE,
    UNIQUE (project_id, techstack_id)
);

CREATE TABLE about_skill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    category VARCHAR(80) NOT NULL,
    months_of_use SMALLINT NOT NULL DEFAULT 0 CHECK (months_of_use >= 0),
    proficiency SMALLINT NOT NULL DEFAULT 3 CHECK (proficiency >= 0)
);

CREATE TABLE about_timelineentry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    title VARCHAR(140) NOT NULL,
    description TEXT NOT NULL,
    entry_type VARCHAR(20) NOT NULL CHECK (entry_type IN ('learning', 'work', 'project'))
);

CREATE TABLE contact_contactsubmission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    message TEXT NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ip_address INET NULL
);

CREATE INDEX projects_project_published_idx
    ON projects_project (published_at DESC, created_at DESC);

CREATE INDEX about_timelineentry_date_idx
    ON about_timelineentry (date DESC);

CREATE INDEX contact_contactsubmission_submitted_idx
    ON contact_contactsubmission (submitted_at DESC);
